# Generated by Django 4.0b1 on 2021-11-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=2)),
                ('foto_usuario', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=100)),
                ('nome_autor', models.CharField(max_length=100)),
                ('data_Entrada', models.DateField()),
                ('foto_livro', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Entrada', models.DateField()),
                ('data_Saida', models.DateField()),
                ('codigo_ibge', models.ImageField(upload_to='')),
                ('foto_livro', models.ImageField(upload_to='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alunos')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.livros')),
            ],
        ),
    ]
